apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-db
data:
  init.sql: |
    CREATE DATABASE snackhub;
    USE snackhub;
    create table customers (
        id INT AUTO_INCREMENT,
        cpf varchar(11) not null,
        first_name varchar(255) not null,
        last_name varchar(255) not null,
        primary key (id));
    alter table customers add constraint UK_customer_cpf unique (cpf);
    create table products (
        id INT AUTO_INCREMENT,
        category varchar(255) not null,
        description varchar(255) not null,
        name varchar(255) not null,
        price decimal(19,2) not null,
        primary key (id));
    CREATE TABLE orders (
        id INT AUTO_INCREMENT,
        customer_id INT,
        observation VARCHAR(255),
        status INT not null,
        payment_status INT not null,
        created_at DATETIME(3),
        FOREIGN KEY (customer_id) REFERENCES customers(id),
        primary key (id));
    CREATE TABLE order_items (
        id INT AUTO_INCREMENT,
        order_id INT,
        product_id INT,
        quantity INT,
        FOREIGN KEY (order_id) REFERENCES orders(id),
        FOREIGN KEY (product_id) REFERENCES products(id),
        primary key (id));