mysql:
  username: root
  password: 123456
  schema: snackhub
  url: snackhub-mysql-db
  port: 3306
  #url: 127.0.0.1:3307

server:
  port: 8080
  undertow:
    threads:
      worker: 10
      io: 2

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  httpclient:
    enable: true

mp:
  url: "https://api.mercadopago.com"