apiVersion: apps/v1
kind: Deployment
metadata:
  name: aplicacao-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: container-app
          image: grupo60fiap2023/snackhub-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_URL
              value: "localhost:3306"
            - name: MYSQL_SCHEMA
              value: "snackhub"
            - name: MYSQL_USERNAME
              value: "root"
            - name: MYSQL_PASSWORD
              value: "123456"
      volumes:
        - name: init-sql
          configMap:
            name: configmap-app
          
